CREATE TABLE [Entt].[Acceptance](
	[Id] [varchar](50) NOT NULL,
	[Version] [int] NOT NULL,
	[ModuleId] [varchar](2) NOT NULL,
	[ConsignmentNo] [varchar](50) NOT NULL,
	[DateTime] [DateTime] NOT NULL,
	[PickupNo] [varchar](10) NULL,
	[TotalConsignment] [int] NULL,
	[IsParent] [bit] NULL,
	[Parent] [varchar](20) NULL,
	[Postcode] [varchar](5) NULL,
	[ParentWeight] [float] NULL,
	[TotalItem] [int] NULL,
	[ProductType] [varchar](10) NULL,
	[ProductTypeDescription] [varchar](100) NULL,
	[PackageType] [varchar](10) NULL,
	[PackageTypeDescription] [varchar](100) NULL,
	[Country] [varchar](50) NULL,
	[Height] [float] NULL,
	[Width] [float] NULL,
	[Length] [float] NULL,
	[Weight] [float] NULL,
	[ItemCategory] [varchar](2) NULL,
	[ItemCategoryDescription] [varchar](50) NULL,
	[TotalBaby] [int] NULL,
	[TotalParent] [int] NULL,
	[RoutingCode] [varchar](50) NULL,
	[TotalWeight] [float] NULL,
	[TotalDimWeight] [float] NULL,
	[Price] [money] NULL,
	[ConsignmentFee] [money] NULL,
	[CourierId] [varchar](30) NULL,
	[CourierName] [varchar](50) NULL,
	[LocationId] [varchar](10) NULL,
	[LocationName] [varchar](50) NULL,
	[BeatNo] [varchar](3) NULL,
	[SystemId] [varchar](3) NULL,
	[SystemName] [varchar](50) NULL,
	[WeightDensity] [float] NULL,
	[WeightVolumetric] [float] NULL,
	[ConsigneeAddressPostcode] [varchar](5) NULL,
	[ConsigneeAddressCountry] [varchar](30) NULL,
	[ShipperAccountNo] [varchar](10) NULL,
	[ShipperAddressPostcode] [varchar](5) NULL,
	[ShipperAddressCountry] [varchar](30) NULL,
	[IposReceiptNo] [varchar](30) NULL,
	[FailPickupReason] [varchar](2) NULL,
	[Comment] [varchar](255) NULL,
	[DropCode] [varchar](2) NULL,
	[LatePickup] [varchar](1) NULL,
	[Pl9No] [varchar](10) NULL,
	[PickupDateTime] [DateTime] NULL,
	[ClerkId] [varchar](10) NULL,
	[DropOption] [varchar](1) NULL,
	[DestinationServiceStandard] [varchar](50) NULL,
	[ExpectedDeliveryDateTime] [DateTime] NULL,
	[DeliveryBranchId] [varchar](10) NULL,
	[DeliveryBranchName] [varchar](50) NULL,
	[IsContract] [bit] NULL,
	[IsBilled] [bit] NULL,
	[FaultPostcode] [varchar](10) NULL,
	[IsMissort] [bit] NULL,
	[MissortLocation] [varchar](10) NULL,
	[MissortDateTime] [DateTime] NULL,
	[IsPupStatCode] [bit] NULL,
	[PupStatCodeId] [varchar](10) NULL,
	[PupStatCodeLocation] [varchar](50) NULL,
	[PupStatCodeDateTime] [DateTime] NULL,
	[ScannerId] [varchar](10) NULL,
	[HubCode] [varchar](10) NULL,
	[CreatedDate] [smalldatetime] NOT NULL,
	[CreatedBy] [varchar](50) NULL,
	[ChangedDate] [smalldatetime] NOT NULL,
	[ChangedBy] [varchar](50) NULL
	)