USE [EnttPlatform]
GO

CREATE TABLE [Entt].[Acceptance](
	[id] [varchar](20) NOT NULL,
	[version] [int] NOT NULL,
	[baby_item] [varchar](20) NULL,
	[dt_received_at_oal_date_field] [datetime] NULL,
	[dt_created_date_field] [datetime] NULL,
	[parent] [varchar](20) NULL,
	[total_consignment_item_number] [int] NULL,
	[is_parent] [tinyint] NULL,
	[number] [varchar](40) NULL,
	[postcode] [varchar](5) NULL,
	[parent_weight_double] [float] NULL,
	[total_item_number] [int] NULL,
	[prodtype] [varchar](10) NULL,
	[prod_type_desc] [varchar](100) NULL,
	[packagetype] [varchar](10) NULL,
	[package_type_desc] [varchar](100) NULL,
	[country] [varchar](10) NULL,
	[height_double] [float] NULL,
	[width_double] [float] NULL,
	[length_double] [float] NULL,
	[weight_double] [float] NULL,
	[item_category] [varchar](2) NULL,
	[item_category_desc] [varchar](50) NULL,
	[total_baby_number] [int] NULL,
	[total_parent_number] [int] NULL,
	[routing_code] [varchar](14) NULL,
	[total_weight_double] [float] NULL,
	[total_dim_weight_double] [float] NULL,
	[price_money] [float] NULL,
	[consignment_fee_money] [float] NULL,
	[sold_to_party_account] [varchar](10) NULL,
	[recipient_ref_no] [varchar](20) NULL,
	[_clerk_id] [varchar](10) NULL,
	[_courier_id] [varchar](10) NULL,
	[location_id] [varchar](4) NULL,
	[location_office_name] [varchar](50) NULL,
	[system_id] [varchar](3) NULL,
	[system_id_desc] [varchar](30) NULL,
	[authorisation_id] [varchar](20) NULL,
	[weight_density_double] [float] NULL,
	[weight_volumetric_double] [float] NULL,
	[acceptance_cut_off_indicator] [varchar](1) NULL,
	[consignee_address_address1] [varchar](50) NULL,
	[consignee_address_address2] [varchar](50) NULL,
	[consignee_address_city] [varchar](50) NULL,
	[consignee_address_post_code] [varchar](10) NULL,
	[consignee_address_state] [varchar](30) NULL,
	[consignee_address_country] [varchar](30) NULL,
	[consignee_name] [varchar](50) NULL,
	[consignee_email] [varchar](50) NULL,
	[consignee_phone] [varchar](15) NULL,
	[consignee_reference_number] [varchar](12) NULL,
	[shipper_account] [varchar](50) NULL,
	[shipper_name] [varchar](50) NULL,
	[shipper_address_address1] [varchar](50) NULL,
	[shipper_address_address2] [varchar](50) NULL,
	[shipper_address_city] [varchar](50) NULL,
	[shipper_address_post_code] [varchar](10) NULL,
	[shipper_address_state] [varchar](30) NULL,
	[shipper_address_country] [varchar](30) NULL,
	[shipper_email] [varchar](50) NULL,
	[shipper_phone] [varchar](15) NULL,
	[shipper_reference_number] [varchar](12) NULL,
	[_i_p_o_s_receipt_no] [varchar](30) NULL,
	[packaging_code] [varchar](2) NULL,
	[packaging_desc] [varchar](20) NULL,
	[day_taken_for_data_entry] [varchar](4) NULL,
	[drop_option_indicator] [varchar](1) NULL,
	[pickup_date_date_field] [datetime] NULL,
	[pl_nine] [varchar](10) NULL,
	[destination_service_standard] [varchar](10) NULL,
	[expected_delivery_date] [datetime] NULL,
	[delivery_branch_id] [varchar](4) NULL,
	[delivery_branch_name] [varchar](50) NULL,
	[is_contract] [tinyint] NULL,
	[is_billed] [tinyint] NULL,
 CONSTRAINT [PK_consignment_initial] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO