CREATE TABLE [Entt].[Unknown](
  [Id] VARCHAR(50) PRIMARY KEY NOT NULL
,[EventType] VARCHAR(10) NOT NULL
,[ScannerId] VARCHAR(10) NOT NULL
,[CourierId] VARCHAR(30) NOT NULL
,[LocationId] VARCHAR(10) NOT NULL
,[Date] VARCHAR(255) NOT NULL
,[Time] VARCHAR(255) NOT NULL
,[ConsignmentNo] VARCHAR(50) NOT NULL
,[Status] VARCHAR(255) NOT NULL
,[PupDateTime] SMALLDATETIME  NULL
,[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
,[CreatedBy] VARCHAR(50) NULL
,[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
,[ChangedBy] VARCHAR(50) NULL
)
