CREATE TABLE [Entt].[Delivery](
  [Id] VARCHAR(50) PRIMARY KEY NOT NULL,
	[Version] [int] NOT NULL,
	[EventName] [varchar](50) NULL,
	[Channel] [varchar](2) NULL,
	[DateTime] SMALLDATETIME NOT NULL,
	[OfficeNo] [varchar](4) NULL,
	[OfficeName] [varchar](30) NULL,
	[OfficeNextCode] [varchar](4) NULL,
	[BeatNo] [varchar](3) NULL,
	[ItemTypeCode] [varchar](2) NULL,
	[Comment] [nvarchar](50) NULL,
	[CourierId] [varchar](15) NULL,
	[CourierName] [varchar](30) NULL,
	[ConsignmentNo] [varchar](30) NULL,
	[Parent] [varchar](30) NULL,
	[DeliveryCode] [varchar](5) NULL,
	[AlternativeAddress] [varchar](100) NULL,
	[RecepientName] [nvarchar](50) NULL,
	[RecepientIc] [varchar](15) NULL,
	[RecepientLocation] [varchar](2) NULL,
	[RecepientLocationDesc] [varchar](30) NULL,
	[AuthorizeName] [nvarchar](50) NULL,
	[PaymentType] [varchar](2) NULL,
	[PaymentTypeDesc] [varchar](30) NULL,
	[PaymentMode] [varchar](2) NULL,
	[PaymentModeDesc] [varchar](50) NULL,
	[ChequeNo] [varchar](10) NULL,
	[BankCode] [varchar](2) NULL,
	[BankCodeDesc] [varchar](50) NULL,
	[TotalPayment] [decimal] NULL,
	[DropCode] [varchar](1) NULL,
	[DropLocation] [varchar](20) NULL,
	[CodAccount] [varchar](20) NULL,
	[BatchName] [varchar](60) NULL,
	[DamageCode] [int] NULL,
	[DataFlag] [varchar](1) NULL,
	[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	[CreatedBy] VARCHAR(50) NULL,
	[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	[ChangedBy] VARCHAR(50) NULL
)
