CREATE TABLE [Entt].[StatusCode](
  [Id] VARCHAR(50) PRIMARY KEY NOT NULL,
	[Version] [int] NOT NULL,
	[Channel] [varchar](2) NULL,
	[DateTime] SMALLDATETIME NOT NULL,
	[OfficeNo] [varchar](4) NULL,
	[OfficeName] [varchar](30) NULL,
	[OfficeNextCode] [varchar](4) NULL,
	[BeatNo] [varchar](3) NULL,
	[ItemTypeCode] [varchar](2) NULL,
	[CourierId] [varchar](15) NULL,
	[CourierName] [varchar](30) NULL,
	[ConsignmentNo] [varchar](30) NULL,
	[BatchName] [varchar](60) NULL,
	[StatusCode] [varchar](2) NULL,
	[StatusCodeDesc] [varchar](50) NULL,
	[DataFlag] [varchar](1) NULL,
	[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	[CreatedBy] VARCHAR(50) NULL,
	[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	[ChangedBy] VARCHAR(50) NULL
)
