CREATE TABLE [PosEntt].[UnknownItem](
  [Id] VARCHAR(50) PRIMARY KEY NOT NULL
,[EventType] VARCHAR(255) NOT NULL
,[ConsignmentNo] VARCHAR(255) NOT NULL
,[CourierId] VARCHAR(255) NOT NULL
,[LocationId] VARCHAR(255) NOT NULL
,[BeatNo] VARCHAR(255) NOT NULL
,[DateTime] SMALLDATETIME NOT NULL
,[DestinationOffice] VARCHAR(255) NOT NULL
,[Comment] VARCHAR(255) NOT NULL
,[Status] VARCHAR(255) NOT NULL
,[Json] VARCHAR(MAX)
,[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
,[CreatedBy] VARCHAR(255) NULL
,[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
,[ChangedBy] VARCHAR(255) NULL
)
