CREATE TABLE [PosEntt].[Unknown](
  [Id] VARCHAR(50) PRIMARY KEY NOT NULL
,[EventType] VARCHAR(255) NOT NULL
,[ScannerId] VARCHAR(255) NOT NULL
,[CourierId] VARCHAR(255) NOT NULL
,[LocationId] VARCHAR(255) NOT NULL
,[Date] VARCHAR(255) NOT NULL
,[Time] VARCHAR(255) NOT NULL
,[ConsignmentNo] VARCHAR(255) NOT NULL
,[Status] VARCHAR(255) NOT NULL
,[PupDateTime] SMALLDATETIME  NULL
,[Json] VARCHAR(MAX)
,[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
,[CreatedBy] VARCHAR(255) NULL
,[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
,[ChangedBy] VARCHAR(255) NULL
)
